name: Build Spring

on:
  workflow_dispatch:
  push:
    paths:
      - 'spring/**'
      - '.github/workflows/build-spring.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        java: ['8', '11'] # error in 16, 17 due to gradle version, which cannot be applied to jdk
    env: # define constant
      PROJECT_PREFIX: spring
    steps:
      - name: Export Global Var
        run: |
          echo "PROJECT_HOME=$PWD" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.Java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Cache Gradle Packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build Spring
        run: |
          cd $PROJECT_HOME/$PROJECT_PREFIX
          ./gradlew clean build -x test -x spring-test:junit --console=plain
